### ISSUE TITLE
Standalone converter should subscribe to costmap updates

### ISSUE THREAD

**Issue by sloretz** [rst-tu-dortmund/costmap_converter#1]
With the default behavior of costmap_2d, the standalone converter appears to do nothing. No polygon markers are published. This is because he standalone converter subscribes only to the topic **/move_base/local_costmap/costmap**

By default the costmap is published once on that topic, and then forever as updates on **/move_base/local_costmap/costmap_updates**. The [static_layer](https://github.com/ros-planning/navigation/blob/jade-devel/costmap_2d/plugins/static_layer.cpp#L224) in costmap_2d has an example of subscribing to updates 

A workaround is to set the parameter **always_send_full_costmap** on the local_costmap to True.

**Comment by doisyg** [comment]
I would be interested to know  more about this issue. I also subscribe do costmap_updates when using a standalone costmap.
Is there another possible mechanism for costmap updates? Like when everything is running in the same node I guess that's the costmap pointer which is passed?

**Comment by croesmann** [comment]
thanks a lot. Fixed.
@doisyg: I am also not aware of any other mechanism in case everything is running in the same node. E.g. in the navigation stack, we have access to the costmap pointer as you said.
