### ISSUE TITLE
Missing <build_type>ament_cmake</build_type> for costmap_converter in ros2 branch

### ISSUE THREAD

**Issue by dkuenster** [rst-tu-dortmund/costmap_converter#13]
https://github.com/rst-tu-dortmund/costmap_converter/blob/c2c8952c46b3e3f1ef2a3e3414f563892670a1d1/costmap_converter/package.xml#L32

You are missing a "<build_type>ament_cmake</build_type>" above line 32.

**Comment by croesmann** [comment]
thanks! should be already fixed ;-)
