### ISSUE TITLE
Wrong return type in the function causing troubles in compiling from source.

### ISSUE THREAD

**Issue by PranavDhulipala** [rst-tu-dortmund/costmap_converter#19]
C:\ws\turtlebot3\src\costmap_converter\include\costmap_converter\costmap_to_polygons.h(305) : error C4716: 'costmap_converter::CostmapToPolygonsDBSMCCH::pointToNeighborCells': must return a value

The above error can be fixed by changing the return type to void in the function pointToNeighborCells in the costmap_to_polygons.h and recompiling.

**Comment by croesmann** [comment]
Thanks and Done! I already fixed that in ros2. However, forgot to do the same in master.
