### ISSUE TITLE
Obstacle circle

### ISSUE THREAD

**Issue by artivis** [rst-tu-dortmund/costmap_converter#5]
How could a circle be describe with the `ObstacleMsg.msg` ??
As of now and since we are dealing with 2D I use a single `geometry_msgs/Point32` in the polygon where its `x` & `y` component describe the circle center and its `z` component describe its radius.  
This is a bit hacky but is there a better way ??

**Comment by croesmann** [comment]
We could add a separate field in `ObstacleMsg.msg` called `radius`.
In case the polygon has just a single point, `radius` could be used to describe a circle.
This is also a bit hacky, but I don't see any other way right now and this also the way how it is done with the footprint definition in package costmap_2d.

**Comment by croesmann** [comment]
done with commit 1e056c5a912f2fbc0a4f8cc8698af8127fb44430

**Comment by artivis** [comment]
Great, thanks !
