### ISSUE TITLE
Is this repo still maintained ?

### ISSUE THREAD

**Issue by artivis** [rst-tu-dortmund/costmap_converter#6]
Just wondering if this repo is still maintained or else if one should work on his own fork ?? (@croesmann )

**Comment by croesmann** [comment]
In principle, yes it is still maintained. But currently, I am writing a lot for my thesis, so my ROS projects come up short :-( I have some updates in the pipeline from a colleague, which I try to push soon.

**Comment by artivis** [comment]
Good news, I will not fork then as I'm actually looking forward to the (possible) merge of PR #4 ^^.  

By then, best of luck for the writing :+1:.
